### PR TITLE
Update README.md

### LINKED ISSUE #4: Improve readme
Hello! 👋

I'd love to see the readme be improved! Particularly with the example use cases. Maybe even linking to a project that uses this plugin in the wild so that a prospective user can see it in action in a real-world scenario.

Something like this maybe? (except tailored to this project) https://gist.github.com/jcbhmr/77de296e4e7b3c42855ea927c7409e53 or https://gist.github.com/jcbhmr/5fa35ec1c7208018e9dce2a9e06af0cf

I am willing to contribute code to do this, I just don't want to be in PR limbo forever. ❤

### PR DESCRIPTION
**Pull request by jcbhmr**
This PR would... (checkboxes track draft progress)
- [x] Add header image
- [x] Add feature emoji list
- [x] Add a .d.ts-like options descriptor
- [x] Add an options table
- [x] Add a "Use cases" section

Closes #4

### CODE REVIEW

**Comment by ManBearTM** [comment]
Awesome work so far! 👍

**Comment by jcbhmr** [comment]
I came back to this PR after two weeks of procrastination (my bad 🙄).

@ManBearTM I'm looking for a usecase (or two) that I could use as an example of _when to use this_ over the default bundling technique. I notice that in the original readme, there was some focus on:

> With the rise in monorepos and native ESM support, it is becoming increasingly popular to release libraries that are meant to be bundled by the consuming application (or even served directly). The support for library mode in Vite is still lacking...

I was wondering if you could elaborate? Maybe a specific example that I could use? 🤔

I'm looking for more ideas outside of my usecase which is: easier mutli-entry-point files for an `exports: { ... }` map in package.json like:
```json
{
  "exports": {
    ".": "./dist/index.js",
    "./*": "./dist/*.js"
  }
}
```

**Comment by ManBearTM** [comment]
Absolutely no worries, just grateful that you are willing to put your time into this!

I’ve been thinking about possible use cases as well, but it is very hard to come up with concrete examples because libraries can be structured so differently.

For my specific use case, I wanted to utilize the very powerful Vite ecosystem for my library, such as dev server, define for env, vitest and various plugins to handle certain files/features. But this library was part of a monorepo and was meant to be consumed by a Next app in that same monorepo, so I had no use for a bundled output (and it would prevent things like lazy loading from working).

Perhaps it would be better with a simple example, I’m imagining something like this:

Two Vite projects, one library and one app. 

The library could be a simple React component library (fx. a button) with some styles in `module.css` format. Its Vite config uses no-bundle (obviously) with a `copy` config targeting the `css` files. The library would also have a simple `index.html` used only for rendering the button when developing.

The app would then consume the library and is able to bundle everything together and scope the `css` module appropriately.

Do you think it makes sense to add something like that? I can supply the code if needed 🙂

**Comment by jcbhmr** [comment]
I'd also recommend changing the description to match the "tagline" that I used (or changing the tagline to match the description; your choice)

Tagline from readme: ⚡ Use Vite for building without the bundling part
Current desc: Use Vite for building without the bundling part.

Also consider adding some GitHub tags (and maybe matching those with the package.json keywords you already have 😉)

@ManBearTM ready for review (I think)

**Comment by jcbhmr** [comment]
@ManBearTM ready for review (I think)

**Review by ManBearTM — APPROVED** [review]
Fantastic work, thank you so much for contributing!

**Pull request merged**
